version: 1
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build'
      include: scope
  - package-ecosystem: 'npm'
    directory: '/app/mobile'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build'
      include: scope
  - package-ecosystem: 'npm'
    directory: '/app/pc'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'build'
      include: scope
